### ISSUE TITLE
Feature Request: Improve recent command navigation

### ISSUE THREAD

**Issue by Runi-c** [rjmatthews62/MooCoder#1]
This is currently my biggest pain point in MooCoder, which has otherwise been an excellent experience!

1. Scroll wheel does not work in the recent commands box just below the output area. Therefore to navigate it one must click inside and use arrow keys.
2. Pressing up/down arrow keys while focused in the command box should insert recent commands in the box, similar to most shells. This would help quickly re-send recent commands, which for me is a common operation while coding (say if I want to re-print the properties of some object so it is more accessible)

**Comment by rjmatthews62** [comment]
I think you'll find Ctrl+Up and Ctrl+Down in the command box will work as desired. (This is the same as BeipeMU)
I will look at putting in scroll wheel handling where appropriate.
